### PR TITLE
Disabled multiple BAM input for sc_exon_mapping

### PR DESCRIPTION
**Pull request by Shians**
* Disabled multiple BAM input for sc_exon_mapping
* Added inactive code to guess barcode and UMI lengths from read header, currently breaks vignette so don't enable yet.

So I think that the multiple BAM file input doesn't actually work. The issue is that by looping over the bam files [this line](https://github.com/LuyiTian/scPipe/blob/master/src/transcriptmapping.cpp#L657) of code is run for each BAM file.  This results in a BAM file that has a structure which looks like

    HEADER1
    RECORDS1
    HEADER2
    RECORDS2
    ....

Rather than the correct

    MERGED_HEADER
    RECORDS1
    RECORDS2
    ....

This means that the BAM file cannot actually be read properly past the first set of records in the merged BAM. Running samtools on such a file will give a "file truncated" warning, but more importantly our sc_gene_counting gives no warnings/errors and I'm not sure what it puts in the count matrix.

### CODE REVIEW

**Comment by PeteHaitch** [comment]
@Shians  This change may be premature because I might have misunderstood the use of multiple input BAMs (based on reading https://github.com/LuyiTian/scPipe/issues/83#issuecomment-409799405)
So perhaps it's the documentation that needs to be clarified before changes to this feature are considered.

**Comment by LuyiTian** [comment]
@PeteHaitch There are two user cases for multi bams as input. 
1) the fastq are demultiplexed and each fastq represent a single cell. then these fastqs can be aligned separately and given as input for sc_exon_mapping, supplied with a dummy cell id vector since we still want to maintain the <cell_id>_<UMI>#original_fastq_name structure for the downstream pipeline, we need to put something to <cell_id>. 

2) there are multiple fastq files but they represent a same pool of cells. This sometime happens when there are multiple lane in the sequencing and multiple fastq like _L001_ _L002 _L003_ were generated. Then one can call sc_trim_barcode -> alignment separately and use multiple bam file as input.

If they were not designed as such, for 1) and 2) one have to merge the fastq at the beginning and put it to the pipeline. At first I thought it was not elegant and sc_exon_mapping was a good time point to merge them instead of before sc_trim_barcode so I wrote it this way. But now I think it may not be a good design. It adds extra complexity to the code with confusing logic. Actually, I am thinking of removing the whole part and let people just merge the fastq at the beginning.


@Shians  I checked my code and the error is I called `sam_hdr_write(of, header);` regardless of the writing mode. I shouldn't write a header if the writing mode is 'a' which means we are appending to an existing bam file. So one solution can be `if(write_mode=="wb"){sam_hdr_write(of, header);}`, so it wont write header for the subsequent bam files. However, we need to make sure the first bam file header contains sufficient information, which is usually the case so I think it is not a concern.

**Comment by PeteHaitch** [comment]
> Actually, I am thinking of removing the whole part and let people just merge the fastq at the beginning.
I think that's a good idea, perhaps supplying an R helper function for users unfamiliar with how to do this at the command line.

**Comment by PeteHaitch** [comment]
@LuyiTian FWIW, my use was kind of weird and not quite (2): I had 1 plate where some wells were in 1 file (true single cells) and some wells were in another file (pooled RNA from 100 cells).

**Comment by Shians** [comment]
I'll close this until further discussion and consensus.

**Pull request closed without merging**
